name: Multi-Arch Build for Go

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  multi-arch-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.1"

      - name: Set environment variables
        run: |
          echo "GOOS=${{ matrix.os }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Build chain and sidecar
        run: |
          make build-test-app && make build
