name: E2E tests
on:
  pull_request:
    paths-ignore:
      - docs/**
    branches:
      - main
      - release/v1.x.x
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
          cache: true
          cache-dependency-path: go.sum
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Pull slinky-dev-base image
        run: docker pull ghcr.io/dydxprotocol/slinky/slinky-dev-base:latest
      - name: tests
        if: env.GIT_DIFF
        run: |
          make test-integration
