name: Tests
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
    paths-ignore:
      - tests/**
      - docs/**

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-tests
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.1

      - name: Git Diff
        uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum

      - name: Tests
        if: env.GIT_DIFF
        run: |
          make test
